services:
  # NestJS Application Service
  app:
    container_name: nestjs-backend-dev:latest
    build: 
      context: .
    ports:
      - '4100:4100'
    # entrypoint: ./start.sh
    env_file:
      - ./.env
    depends_on:
      - redis

  # PostgreSQL Service
  # db:
  #   image: postgres:16-alpine
  #   container_name: bingo-dev-postgres-db
  #   env_file:
  #     - ./.env
  #   ports:
  #     - '5678:5432'
  #   volumes:
  #     - /var/lib/postgresql/data:/var/lib/postgres

  # Redis Service
  redis:
    image: redis:7
    container_name: redis-server
    ports:
      - '6378:6379'
