name: CI/CD--Main
on:
  pull_request_target:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  deploy-pr-for-testing:
    environment:
      name: preview
      url: ${{ steps.deploy.outputs.preview-url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to branch
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test

      - id: deploy
        name: Pull Request Deploy
        uses: hngprojects/pr-deploy@main
        with:
          server_host: ${{ secrets.SERVER_HOST }}
          server_username: ${{ secrets.SERVER_USERNAME }}
          server_password: ${{ secrets.SERVER_PASSWORD }}
          server_port: ${{ secrets.SERVER_PORT }}
          comment: true
          context: '.'
          dockerfile: 'dockerfile'
          exposed_port: '4300'
          host_volume_path: '/var/'
          container_volume_path: '/var/'
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Print Preview Url
        run: |
          echo "Preview Url: ${{ steps.deploy.outputs.preview-url }}"

  deploy-to-server:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Images
        run: |
          docker build -t nestjs-backend-main:latest .

      - name: Save Docker Images as Tarballs
        run: |
          docker save -o nestjs-backend-main.tar nestjs-backend-main:latest

      - name: Upload Docker Image to Server using SCP
        env:
          SERVER_USERNAME: ${{ secrets.SERVER_USERNAME }}
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
        run: |
          sshpass -p "${SERVER_PASSWORD}" scp -o StrictHostKeyChecking=no nestjs-backend-main.tar docker-compose.prod.yml ${SERVER_USERNAME}@${SERVER_HOST}:/home/teamalpha/bingo_be/prod

      - name: Load Docker Image on Server and Run via Docker Compose
        env:
          SERVER_USERNAME: ${{ secrets.SERVER_USERNAME }}
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
        run: |
          sshpass -p "${SERVER_PASSWORD}" ssh -o StrictHostKeyChecking=no ${SERVER_USERNAME}@${SERVER_HOST} << 'EOF'
            cd /home/teamalpha/bingo_be/prod
            sudo docker load -i nestjs-backend.tar
            rm 
            sudo docker-compose -f docker-compose.prod.yml up -d
          EOF
